### ISSUE TITLE
cpu_features: Build error for MinGW

### ISSUE THREAD

**Issue by mmuetzel** [DrTimothyAldenDavis/GraphBLAS#181]
When trying to build GraphBLAS as part of SuiteSparse for MinGW (using MSYS2), compilation fails with the following error:
```
[  7%] Building C object CMakeFiles/graphblas.dir/Source/GB_cpu_features_support.c.obj
In file included from D:/MINGW-packages-mmuetzel/mingw-w64-suitesparse/src/build-MINGW64/GraphBLAS/Source/GB_cpu_features_support.c:16:
D:/MINGW-packages-mmuetzel/mingw-w64-suitesparse/src/build-MINGW64/GraphBLAS/cpu_features/src/hwcaps.c:110:2: error: #error "This platform does not provide hardware capabilities."
  110 | #error "This platform does not provide hardware capabilities."
      |  ^~~~~
D:/MINGW-packages-mmuetzel/mingw-w64-suitesparse/src/build-MINGW64/GraphBLAS/cpu_features/src/hwcaps.c: In function 'GetHardwareCapabilitiesFor':
D:/MINGW-packages-mmuetzel/mingw-w64-suitesparse/src/build-MINGW64/GraphBLAS/cpu_features/src/hwcaps.c:152:26: warning: implicit declaration of function 'GetElfHwcapFromGetauxval'; did you mean 'GetElfHwcapFromProcSelfAuxv'? [-Wimplicit-function-declaration]
  152 |   unsigned long hwcaps = GetElfHwcapFromGetauxval(type);
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~
      |                          GetElfHwcapFromProcSelfAuxv
D:/MINGW-packages-mmuetzel/mingw-w64-suitesparse/src/build-MINGW64/GraphBLAS/cpu_features/src/hwcaps.c: In function 'CpuFeatures_GetPlatformPointer':
D:/MINGW-packages-mmuetzel/mingw-w64-suitesparse/src/build-MINGW64/GraphBLAS/cpu_features/src/hwcaps.c:168:10: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  168 |   return (const char *)GetHardwareCapabilitiesFor(AT_PLATFORM);
      |          ^
D:/MINGW-packages-mmuetzel/mingw-w64-suitesparse/src/build-MINGW64/GraphBLAS/cpu_features/src/hwcaps.c: In function 'CpuFeatures_GetBasePlatformPointer':
D:/MINGW-packages-mmuetzel/mingw-w64-suitesparse/src/build-MINGW64/GraphBLAS/cpu_features/src/hwcaps.c:172:10: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  172 |   return (const char *)GetHardwareCapabilitiesFor(AT_BASE_PLATFORM);
      |          ^
make[4]: *** [CMakeFiles/graphblas.dir/build.make:3058: CMakeFiles/graphblas.dir/Source/GB_cpu_features_support.c.obj] Fehler 1
```

Output from the configuration step:
```
( cd GraphBLAS && make )
make[1]: Verzeichnis „/d/MINGW-packages-mmuetzel/mingw-w64-suitesparse/src/build-MINGW64/GraphBLAS“ wird betreten
( cd build && cmake -G"MSYS Makefiles" -DCMAKE_INSTALL_PREFIX="/mingw64" -DCMAKE_BUILD_TYPE=Release -DENABLE_CUDA=OFF -DBLA_VENDOR=OpenBLAS .. && make --jobs=8 )
-- Building SuiteSparse:GraphBLAS version: v7.3.3, date: Dec 1, 2022
-- GraphBLAS C API: v2.0, date: Nov 15, 2021
-- Source:        D:/MINGW-packages-mmuetzel/mingw-w64-suitesparse/src/build-MINGW64/GraphBLAS
-- Build:         D:/MINGW-packages-mmuetzel/mingw-w64-suitesparse/src/build-MINGW64/GraphBLAS/build
-- The C compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/msys64/mingw64/bin/gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Install rpath:
-- Build   rpath: D:/MINGW-packages-mmuetzel/mingw-w64-suitesparse/src/build-MINGW64/GraphBLAS/build
-- Build type:    Release
-- Looking for a Fortran compiler
-- Looking for a Fortran compiler - C:/msys64/mingw64/bin/gfortran.exe
-- The Fortran compiler identification is GNU 12.2.0
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: C:/msys64/mingw64/bin/gfortran.exe - skipped
-- Fortran: GNU
-- CUDA: not enabled
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_Fortran: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- cpu_features (by google.com): enabled
-- Building dynamic GraphBLAS library
-- Performing Test TEST_FOR_STDATOMIC
-- Performing Test TEST_FOR_STDATOMIC - Success
-- ANSI C11 atomics: OK. -latomic not needed
-- CMAKE OpenMP libraries:    C:/msys64/mingw64/lib/libgomp.dll.aC:/msys64/mingw64/lib/libmingwthrd.aC:/msys64/mingw64/lib/libmingwthrd.a
-- CMAKE OpenMP include:
-- CMAKE OpenMP C flags:      -fopenmp
-- CMAKE C flags: -march=nocona -msahf -mtune=generic -O2 -pipe -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong -std=c11 -lm -Wno-pragmas  -fexcess-precision=fast  -fcx-limited-range  -fno-math-errno  -fwrapv  -O3 -DNDEBUG -fopenmp
-- Skipping the demos in GraphBLAS/Demo
-- Installation will be system-wide (requires 'sudo make install')
-- ------------------------------------------------------------------------
-- SuiteSparse CMAKE report for: graphblas
-- ------------------------------------------------------------------------
-- install in /mingw64: true
-- install in SuiteSparse/lib and SuiteSparse/include: false
-- build type:           Release
-- NSTATIC:              true (do not build static library)
-- use OpenMP:           yes
-- C compiler:           GNU
-- C flags:              -march=nocona -msahf -mtune=generic -O2 -pipe -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong -std=c11 -lm -Wno-pragmas  -fexcess-precision=fast  -fcx-limited-range  -fno-math-errno  -fwrapv  -O3 -DNDEBUG -fopenmp
-- C++ compiler:
-- C++ flags:
-- C Flags release:      -O3 -DNDEBUG
-- C++ Flags release:
-- compile definitions:
-- ------------------------------------------------------------------------
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    BLA_VENDOR


-- Build files have been written to: D:/MINGW-packages-mmuetzel/mingw-w64-suitesparse/src/build-MINGW64/GraphBLAS/build
```

**Comment by mmuetzel** [comment]
Changing the build command to the following avoids the compilation error:
```
cd build && cmake -G"MSYS Makefiles" -DCMAKE_INSTALL_PREFIX="/mingw64" -DCMAKE_BUILD_TYPE=Release -DENABLE_CUDA=OFF -DBLA_VENDOR=OpenBLAS -DGBNCPUFEAT=ON .. && make --jobs=8
```

It would be nice if `GBNCPUFEAT` could be set by default when compiling for Windows.

**Comment by DrTimothyAldenDavis** [comment]
I can't disable it for all builds on Windows, because if I do not have it, C=A*B is MUCH slower for the case when A is sparse and B is full, or visa versa.

When building on Windows, the gcc, icx, icc, and clang compilers all support the use of CPU_FEATURES, at least on the x86 platform.  This allows me to use AVX2 and/or AVX512 on the x86 platform.

I could disable CPU_FEATURES if GraphBLAS is being compiled for MSYS2 but I need to how the pre #defines that tell me when that is true.

**Comment by DrTimothyAldenDavis** [comment]
Is `__MINGW32__` or `__MINGW64__` defined?

The confusing thing is that you are using the gcc compiler, and in my sequence of tests in this file: https://github.com/DrTimothyAldenDavis/GraphBLAS/blob/stable/Source/GB_compiler.h, if gcc is in use inside MS Visual Studio, then I assume gcc can compile the cpu_features package.

I test for the MINGW platform further down.  Should that test be moved up?  In other words, for MINGW64 on Windows, will it always require the CPU_FEATURES to be disabled, even if gcc is in use?

**Comment by mmuetzel** [comment]
`__MINGW32__` should be defined for the 32-bit MinGW targets. `__MINGW32__` and `__MINGW64__` should be defined for the 64-bit MinGW targets.
IIUC, those variables indicate which toolchain of is used (specifically which set of headers describe the C runtime API).
Afaict, both Clang (if not in MSVC mode) and GCC define `__GNUC__` (independent of the target platform).

If the block starting with `#elif defined ( __MINGW32__ ) || defined ( __MINGW64__ )` should be effective, it would probably be necessary to move it in front of the block starting with `#elif defined ( __GNUC__ )`.
It would also be possible to simplify that condition to ``#elif defined ( __MINGW32__ )`. The second part of the existing condition is basically redundant afaict.

I'm not sure what you mean by "if gcc is in use inside MS Visual Studio". I don't know if gcc can be used inside MS Visual Studio. MSVC and GCC are two different sets of compilers (+headers/runtime/...) iiuc.

**Comment by DrTimothyAldenDavis** [comment]
Thanks for the description.  I can move up the MINGW32 block of code in that file so it appears before GCC, but after the Intel compiler test.

MS Visual Studio can be configured so that it uses gcc:  https://devblogs.microsoft.com/cppblog/use-any-c-compiler-with-visual-studio/ .

**Comment by mmuetzel** [comment]
> MS Visual Studio can be configured so that it uses gcc: https://devblogs.microsoft.com/cppblog/use-any-c-compiler-with-visual-studio/ .

Ah. Didn't know that. Thanks for the link.
But iiuc, that is for cross-compilation to Linux or Android (not for native Windows targets). So, moving the test for MinGW up in the chain shouldn't interfere with that either.

**Comment by DrTimothyAldenDavis** [comment]
Oops.  I pushed the change to the wrong branch.  I added it to the v733 branch just now, as I had intended to do.  Sorry for the confusion.

**Comment by mmuetzel** [comment]
Building with gcc works fine with the `v733` branch:
```
...
[100%] Linking C shared library libgraphblas.dll
[100%] Built target graphblas
```

Building with clang still fails:
```
[  7%] Building C object CMakeFiles/graphblas.dir/Source/GB_cpu_features_support.c.obj
[  7%] Building C object CMakeFiles/graphblas.dir/Source/GB_cumsum.c.obj
[  7%] Building C object CMakeFiles/graphblas.dir/Source/GB_dealloc_memory.c.obj
In file included from D:/SVN/Octave/GraphBLAS/Source/GB_cpu_features_support.c:16:
D:/SVN/Octave/GraphBLAS/cpu_features/src/hwcaps.c:110:2: error: "This platform does not provide hardware capabilities."
#error "This platform does not provide hardware capabilities."
 ^
D:/SVN/Octave/GraphBLAS/cpu_features/src/hwcaps.c:152:26: warning: call to undeclared function 'GetElfHwcapFromGetauxval'; ISO C99 and later do not
      support implicit function declarations [-Wimplicit-function-declaration]
  unsigned long hwcaps = GetElfHwcapFromGetauxval(type);
                         ^
[  7%] Building C object CMakeFiles/graphblas.dir/Source/GB_debugify_ewise.c.obj
[  8%] Building C object CMakeFiles/graphblas.dir/Source/GB_debugify_mxm.c.obj
1 warning and 1 error generated.
make[2]: *** [CMakeFiles/graphblas.dir/build.make:3058: CMakeFiles/graphblas.dir/Source/GB_cpu_features_support.c.obj] Fehler 1
make[2]: *** Es wird auf noch nicht beendete Prozesse gewartet....
[  8%] Building C object CMakeFiles/graphblas.dir/Source/GB_debugify_reduce.c.obj
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/graphblas.dir/all] Fehler 2
make: *** [Makefile:136: all] Fehler 2
```

**Comment by mmuetzel** [comment]
I opened #182 which allows building for MinGW using clang and gcc.

**Comment by DrTimothyAldenDavis** [comment]
I think this is resolved now.
